services:
  - type: web
    name: khrdt-backend
    env: node
    buildCommand: cd backend && npm ci --omit=dev  
    startCommand: cd backend && npm start
    nodeVersion: 20.0.0 
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: khrdt-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production