services:
  - ype: web
    name: khrdt-backend
    env: node
    nodeVersion: 20.0.0  # Use LTS version
    buildCommand: |
      cd backend && 
      npm install --omit=dev --prefer-offline --no-audit
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: khrdt-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production